### ISSUE TITLE
Add support for nushell

### ISSUE THREAD

**Issue by bonitao** [NathanVaughn/vscode-task-runner#45]
As with bash, nu requires -c when invoked for running commands. However, it is considered an unknow shell and does not get the same suffix as bash.  Repro, powered by pkgx.sh and pipx:

```
nu -c 'pkgx +pypa.github.io/pipx pipx run vscode-task-runner build'
[1/3] Executing task "gradle-build": /opt/homebrew/bin/nu ./gradlew assemble
Error: nu::shell::file_not_found

  × File not found
   ╭─[source:1:1]
 1 │ nu
   · ▲
   · ╰── Could not access file './gradlew assemble': No such file or directory (os error 2)
   ╰────

Task "gradle-build" returned with exit code 1
```

https://github.com/NathanVaughn/vscode-task-runner/blob/3a6eda8b0786d319fd18fad7c53d021256be73a1/vtr/helpers.py#L48 to be `if shell_basename.endwith("sh") or shell_basename == "nu":`. However, it may be more elegant to add a dedicated shell type to nu. 

Happy to send a PR if that makes sense.

**Comment by NathanVaughn** [comment]
Thanks for pointing this out! Take a look at #46. I was going to avoid adding a special case for `nu`, but leave it as an unknown shell and properly implement the same behavior as VS Code of adding `-c` when the shell type is not recognized.

**Comment by bonitao** [comment]
Excellent! Reviewed and approved.

**Comment by NathanVaughn** [comment]
Version 1.2.0 has been published to PyPi to fix this
