### ISSUE TITLE
Add support to args appending, not only flags

### ISSUE THREAD

**Issue by davireis** [NathanVaughn/vscode-task-runner#51]
When I run `vtr test`, it results in 

` Executing task "test": C:\Program Files\PowerShell\7\pwsh.exe -Command pnpm turbo --filter ./guis/web test`, which will itself eventually call `vitest -c vitest.unit.config.ts --run`. All fine.

It turns out, however, that sometimes I want to pass a reporter to the vitest call, which can be done with `vitest -c vitest.unit.config.ts --run -- --reporter=json`. Notice the appended `-- --reporter=json`. 

The bad news is that vtr only allow appending `--flag`, it does not allow appending `arg` because it consider `arg` a potential second task to be run. It does seem to me that vtr should treat `--`  as end of parameters and passthrough everything after it, which is reasonably well defined unix semantics. In my particular case, this would be strange, but it would work: `vtr run test -- -- --reporter=json`.

**Comment by NathanVaughn** [comment]
Thanks for the feature request, I'm happy to hear someone else finds this tool useful other than myself. I implemented this in the [feature/more-extra-args](https://github.com/NathanVaughn/vscode-task-runner/tree/feature/more-extra-args) branch. If you can, check it out and let me know if it works like you expect. I did add some test cases to check this, along with your example: https://github.com/NathanVaughn/vscode-task-runner/blob/89feafbac2a75128a39659ac3f8a74e96060d07f/tests/test_console.py#L8-L28

**Comment by davireis** [comment]
Thanks @NathanVaughn , code looks amazing. I am finding the tool really useful, I use it in cicd and in interactive development. It helps me guarantee that the IDE flows do not rot since they are never exercised automatically.

**Comment by davireis** [comment]
Hey @NathanVaughn ,

I'm just adding a thank you for writing up vscode-task-runner. You may enjoy seeing the description of how I use it here: https://medium.com/@daviws/writing-a-portable-codebase-3c4cb681f763.
